apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-api
  name: weather-api
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
        - name: weather-api
          image: default-route-openshift-image-registry.apps.ocp4.ocp.local/sample-app/weather-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
            
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080;http://+:8081"  # Binding to ports
          livenessProbe:
            httpGet:
              path: /weatherforecast
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /weatherforecast
              port: 8080
              scheme: HTTP    
            initialDelaySeconds: 10
            periodSeconds: 10      
